language: generic

# sudo: required

# os: linux
language: generic 
services:
  - docker

before_install: 
  - docker build -t dgheart/docker-react -f Dockerfile.dev .

script: 
  - docker run dgheart/docker-react npm run test -- --coverage

deploy: 
  - provider: elasticbeanstalk
  - region: "us-east-2"
  - app: "docker-react"
  - env: "DockerReact-env"
  - bucket_name: "elasticbeanstalk-us-east-2-837731769146"
  - bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
