

language: generic 
services:
  - docker

before_install: 
  - docker build -t dgheart/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true dgheart/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-837731769146"
  bucket_path: "docker-react"
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master
