# language: generic

# sudo: required

# os: linux

services:
  - docker

before_install: 
  - docker build -t dgheart/docker-react -f Dockerfile.dev .

script: 
  - docker run dgheart/docker-react npm run test -- --coverage
