# sudo: required
os: linux
language: node_js
node_js:
  - 12
services:
  - docker
before_install: 
  - docker build -t dgheart/docker-react -f Dockerfile.dev .
script: 
  - docker run dgheart/docker-react npm run test -- --coverage